/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#29b265268a91636a25d941c6e6e92da131f3c924
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _NumberDecs, _BooleanDecs, _NullDecs, _KeywordDecs, _PunctuatorDecs, _ListDecs, _AnyDecs;
import { i, spam as m } from '@bablr/boot';
import { triviaEnhancer } from '@bablr/helpers/trivia';
import * as productions from '@bablr/helpers/productions';
import { buildString, buildBoolean, buildIdentifier } from '@bablr/helpers/builders';
import { Node, CoveredBy, AllowEmpty, InjectFrom } from '@bablr/helpers/decorators';
import * as Space from '@bablr/language-en-blank-space';
import { eat } from '@bablr/helpers/grammar';
export const dependencies = {
  Space
};
export const canonicalURL = 'https://github.com/bablr-lang/language-en-scheme';
export const escapables = new Map(Object.entries({
  n: '\n',
  r: '\r',
  t: '\t'
}));
export const grammar = triviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  *eatMatchTrivia() {
    if (yield i`match(/[ \n\r\t]/)`) {
      yield i`eat(#:<*Space:Space />)`;
    }
  }
}, class SchemeGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "SExpression"], [Node, 2, "String"], [[AllowEmpty, Node], 2, "StringContent"], [_NumberDecs, 2, "Number"], [Node, 2, "Integer"], [Node, 2, "UnsignedInteger"], [_BooleanDecs, 2, "Boolean"], [_NullDecs, 2, "Null"], [_KeywordDecs, 2, "Keyword"], [_PunctuatorDecs, 2, "Punctuator"], [_ListDecs, 2, "List"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_NumberDecs = [CoveredBy('Expression'), Node], _BooleanDecs = [CoveredBy('Expression'), Node], _NullDecs = [CoveredBy('Expression'), Node], _KeywordDecs = [Node, InjectFrom(productions)], _PunctuatorDecs = [Node, InjectFrom(productions)], _ListDecs = [AllowEmpty, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), Symbol.for('@bablr/fragment'))]({
    value: {
      productionName
    }
  }) {
    // needed for the trivia plugin
    yield eat(m`<${buildIdentifier(productionName)} />`);
  }
  *SExpression() {
    yield i`eat(openToken: <*Punctuator '(' {balanced: '(' balancedSpan: 'SExpression'} />)`;
    yield i`eatMatch(<Any /> [
        <NullTag 'null' />
      ])`;
    yield i`eat(closeToken: <*Punctuator ')' { balancer: true } />)`;
  }
  *String() {
    yield i`eat(openToken: <*Punctuator '"' { balanced: '"', balancedSpan:'String' } />)`;
    yield i`eat(content: <*StringContent />)`;
    yield i`eat(closeToken: <*Punctuator '"' { balancer: true } />)`;
  }
  *StringContent() {
    let esc, lit;
    do {
      esc = (yield i`match('\\')`) && (yield i`eat(@:<EscapeSequence />)`);
      lit = yield i`eatMatch(/[^\r\n\\"\g]+/)`;
    } while (esc || lit);
  }
  *Number() {
    yield i`eat(wholePart: <Integer /> { noDoubleZero: true matchSign: '-' })`;
    let fs = yield i`eatMatch(fractionalSeparatorToken: <*Punctuator '.' />)`;
    if (fs) {
      yield i`eat(fractionalPart: <Integer />)`;
    } else {
      yield i`eat(fractionalPart: null)`;
    }
    let es = yield i`eatMatch(exponentSeparatorToken: <*Punctuator /[eE]/ />)`;
    if (es) {
      yield i`eat(exponentPart: <Integer /> { matchSign: /[+-]/ })`;
    } else {
      yield i`eat(exponentPart: null)`;
    }
  }
  *Integer({
    value: props,
    ctx
  }) {
    const {
      matchSign = null
    } = props && ctx.unbox(props) || {};
    if (matchSign) {
      yield i`eatMatch(signToken: <*Punctuator ${matchSign} />)`;
    } else {
      yield i`eat(signToken: null)`;
    }
    yield i`eat(value: <*UnsignedInteger />)`;
  }
  *UnsignedInteger() {
    yield i`eat(/\d+/)`;
  }
  *Boolean() {
    yield i`eat(sigilToken: <*Keyword /#t|#f/ />)`;
  }
  *Null() {
    yield i`eat(sigilToken: <*Keyword 'null' />)`;
  }
  *Keyword() {}
  *Punctuator() {}
  *List() {}
  *Any() {}
});